### ISSUE TITLE
Implement flag sqrlonly

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/wordpress-sqrl-login#17]

**Comment by brianoflondon** [comment]
I'm not sure if Wordpress is going to allow the deletion of the basic method of having an account. That's going to be very interesting. Once you have an email in the system, there's always the chance of a password reset to be performed.

**Comment by kalaspuffar** [comment]
Hi @brianoflondon

I have a hard time keeping these features apart.

But sqrlonly is similar to disabled but with only password login so that's doable.

But hardlock disabling external changes are harder, maybe I will set the flag and inform the user on the profile page that it is not possible at the moment.

Best regards
Daniel
