### ISSUE TITLE
Move login with SQRL to the main login window outside of "Log in with username and password"

### ISSUE THREAD

**Issue by aitorpazos** [kalaspuffar/wordpress-sqrl-login#23]
As a user wanting to use Sqrl on a site to authenticate, it is confusing having to select the "Log in with username and password" to get the Sqrl QR code and button presented to me.

I'd rather want to get it presented on the main login page instead:
![image](https://user-images.githubusercontent.com/2015196/61061222-c04a8380-a3f3-11e9-8fc5-38f1d0faebb5.png)

I think this would improve the experience of using Sqrl by reducing the number of clicks and it would de-couple Sqrl from username/password mechanism.

**Comment by aitorpazos** [comment]
Playing a bit more with a local installation I noticed that that first login screen (shown in the screenshot) is only presented to users when Jetpack plug-in is used and the "Allow users to log into this site using WordPress.com accounts" option enabled. Thus, I think this is more a Jetpack issue than and issue of this project. Reported at https://github.com/Automattic/jetpack/issues/13033

**Comment by jeherve** [comment]
I replied in the Jetpack issue, but I think that is something that could be tweaked in this plugin to improve compatibility with the Jetpack plugin. To default to the regular login form with the SQRL options, you can add the following filter to the plugin:

```php
add_filter( 'jetpack_sso_default_to_sso_login', '__return_false' );
```
