### ISSUE TITLE
wordpress.com diverting me from my login.

### ISSUE THREAD

**Issue by adrapper** [kalaspuffar/wordpress-sqrl-login#52]
Hi,

I have been using SQRL WP plugin for a while... fantastic...

I have not changed my host, I am with wordpress.com but now when I try to login I am diverted to https://wordpress.com/log-in?redirect_to....

**To Reproduce**

Go to https://madmowers.uk/   

At bottom of the page click 'login'

**Expected behavior**

I used to go to a page with a SQRL login.

Now I am taken to a wordpress.com log in page. 

This appears to happen on all browsers/OS even on computers I have not used before.

**Comment by kalaspuffar** [comment]
Hi @adrapper 

I see the problem, sadly this is not something the plugin does. The first interaction of the plugin is after you've landed on your login page.

So I'm not really sure how to help you. Perhaps another plugin redirect you, maybe the new version of WordPress does something funky, or perhaps the WordPress.com team have made some change to your site. :(

I think you need to contact WordPress support.

Please keep me informed if I can be of assistance.

Best regards
Daniel

**Comment by adrapper** [comment]
Having chatted with WP support today they say...

"It looks like you would need to disable the Secure Sign-On feature. Here are more details: https://en.support.wordpress.com/using-membership-plugins/

To do that, you would need to set a password for your WP Admin Dashboard here: https://theredpill.report/wp-admin/profile.php

And then click on "My Sites" > Manage > Settings > Security

And disable the option below "WordPress.com log in"

I have not yet worked through this... but thought I would pass it on as it for now. 

Andrew

**Comment by adrapper** [comment]
Yay... 

Turned off "Allow users to log in to this site using WordPress.com accounts" and we are back in business. 

![Screen Shot 2019-11-17 at 14 05 50](https://user-images.githubusercontent.com/1552796/69008565-aaba0d00-0943-11ea-994c-b7e0d8122f83.jpg)

**Comment by kalaspuffar** [comment]
Hi @adrapper 

Do you feel we have resolved the issue? Can I close it?

Best regards
Daniel

**Comment by adrapper** [comment]
Yes. 

Back to fantastic!

But do you need to note this fix in the installation notes or maybe... I don't know can this setting be part of the setup, because there must be thousands of people on Wordpress.com and any that try this may well be defaulted to using the wordpress.com login as I was.

**Comment by kalaspuffar** [comment]
Hi @adrapper 

Great idea, I will write something up when I get some time. Or if you want to add it, a PR is always welcome. I think it could be added to the plugin documentation with another screenshot, perhaps. 

Not sure what the correct way to document similar things in the WordPress plugin community, so I have to look into that as well if I don't get some help :)

Best regards
Daniel
